voxpupuli/pypuppetdb

setup.cfg
Enables "yum install pypuppetdb" to pull in the other python modules it needs to work
=> Add requires setting to bdist_rpm section of setup.cfg

packaging/rpm/python-pypuppetdb.spec
I've crafted a spec file to build an RPM named python-pypuppetdb which should work on most RH-flavour distros, but may need some later versions of packages building on some platforms.
I have tested it on CentOS 7 - I built updated versions of python-requests and python-urllib3 from Fedora 21.
I didn't get the tests working in the mock environment so I made them optional with a ```--with tests``` flag.
I didn't build the docs because they're not included in the tarball uploaded to pypi.python.org, which I used as the Source.
All RPMs are in my repo at http://repo.yo61.com/el/7
=> Add RPM spec file

pypuppetdb/__init__.py, pypuppetdb/api/__init__.py, setup.cfg, test-requirements.txt, tests/test_baseapi.py
Hey there,
In several environments (like ours), we place PuppetDB behind haproxy with authentication (others may use Nginx or Apache).  We're also serving this at the URL http://www.example.com/puppetdb/ which we need to support.
While doing this, I also updated py.test and setup coverage reporting for the unit tests :smile: 
Cheers
Fotis
=> Implemented optional HTTP basic authentication and url path

pypuppetdb/api/v3.py, pypuppetdb/types.py, tests/test_types.py
Hello there, here's my first pull request for you :smile: 
This adds some more advanced information to each event which I intend to display on Puppetboard when users are drilling into events and want to know exactly where the problem originated.
e.g.
```python
In [1]: from pypuppetdb import connect
In [2]: db = connect(api_version=3, host='puppetdb', port=8080)
In [3]: events = list(db.events('["=", "report", "5ba5a56b67e05a98bb2dcf9124e74210d7baccbf"]'))                  
In [4]: event = events[0]
In [5]: event.item
Out[5]:
{u'class': u'Jenkins::Builder',
u'execution_path': [u'Stage[main]',
u'Jenkins::Builder',
u'Package[apache2-dev]'],
u'line_number': 80,
u'message': u"ensure changed 'purged' to 'latest'",
u'new': u'latest',
u'old': u'purged',
u'property': u'ensure',
u'source_file': …
```
=> Added class, execution path, source file and line number to event items

CHANGELOG.rst, pypuppetdb/utils.py, tests/test_utils.py
As the name suggests it provides a standard way for pypuppetdb code
ro run standard version comparisons. This function is built off the examples and tests provided in http://stackoverflow.com/questions/1714027/version-number-comparison
The initial intent of this function was to check the Version of PuppetDB
running and check if it is version 3.0 or higher and throw an error
if it failed. In attempting to do so I broke all existing automated
test cases, will have to implement that check in a different way.
=> pypuppetdb/utils: Adding a new utility function versioncmp

pypuppetdb/api/__init__.py, pypuppetdb/types.py, tests/test_baseapi.py, tests/test_types.py
Fixed https://github.com/puppet-community/pypuppetdb/issues/60
The Nodes endpoint now has available a latest_report_status and a latest_report_hash
strings to easily tie it to it's latest report. The latest_report_status
key does not report on noop runs and setting latest_report_hash to a default
None to maintain backward compatability.
The Catalogs endpoint exposes a 'code_id' field that is current unused
but will be used to tie a catalog to the Puppet code that generated the
catalog.
All endpoints now support POST requests. Adding a test case testing against
a DELETE request (non-GET or non-POST requests raise an APIError). Could
not make a test case testing specifically against a POST method in the
last request.
=> pypuppetdb: Adding support for new features available in 3.2.0

pypuppetdb/api/__init__.py, pypuppetdb/types.py, tests/test_types.py
This fixes https://github.com/voxpupuli/pypuppetdb/issues/81
This undoes https://github.com/voxpupuli/pypuppetdb/pull/76
This new functionality was not thoroughly tested, the main symtom is that
the timestamps returned by the expanded resource events data are in a
format that Python cannot parse. Namely tiemzones are returned with -04:00
and Python 2.x cannot parse that, not sure about Python 3.
=> pypuppetdb/types.py: Remove :class:`pypuppetdb.types.Report` events

pypuppetdb/types.py
Use `dict.itervalues()` by default, but fall back to `dict.values()` if it doesn't exist.
=> pypuppetdb/types.py: fix Python3 compatibility

docs/api.rst, pypuppetdb/QueryBuilder.py, pypuppetdb/api.py, pypuppetdb/types.py, tests/test_querybuilder.py
This resolves https://github.com/voxpupuli/pypuppetdb/issues/77
This PR adds a new file QueryBuilder.py which enables the creation of PuppetDB queries in an OOP style where the user can create queries ranging from a single equals query, invoked with `EqualsOperator("certname", "node1.example.com")` to very complex queries with multiple tiers of ands, ors and not queries. All while being able to add more clauses just as easily as adding elements to a list object.
=> Query builder

.travis.yml, requirements.txt
I'm looking into running puppetboard under python 3 and want to make sure that pypuppetdb will work on the default python 3.x version on Ubuntu 16.04. Looks good so far :-)
=> Run Travis tests under newer python versions

pypuppetdb/api.py, pypuppetdb/types.py, tests/test_types.py
This resolves #101 
See the [Release Notes](https://docs.puppet.com/puppetdb/4.2/release_notes.html) for more information.
=> Adding API Endpoints and Additional Functionality for PuppetDB 4.2.0

pypuppetdb/api.py, pypuppetdb/types.py, tests/test_types.py
If a node has a 'noop' status and go unreported, it was reporting it as 'noop' instead of 'unreported'.
That doesn't happen for puppetdb < 4.1x, nor to other status (unchanged, failed or changed).
I assume that creating the `Node` object is not considered a valid API use, and that this change would be considered non-breaking change because the api.py is still called the same way and return the same object. 
This problem doesn't happen in report, because it doesn't have a concept of 'unreported'.
=> puppetdb/api.py|types.py: Unreported nodes (#108)

README.rst, pypuppetdb/QueryBuilder.py, tests/test_querybuilder.py
Working on puppetboard, I needed some operators documented here 
https://docs.puppet.com/puppetdb/3.2/api/query/v4/operators.html#subquery-operators
List of endpoints authorized for the Subquery operator come from 3.2. 3.0 miss some of them, but available ones may still be usable.
Client example code -
`
events_query = AndOperator()
events_query.add(EqualsOperator('status', 'noop'))
log.error(events_query)
subquery = SubqueryOperator('events')
subquery.add_query(events_query)
log.error(subquery)
extract_query = ExtractOperator()
extract_query.add_field(str('certname'))
extract_query.add_query(subquery)
log.error(extract_query)
in_query = InOperator("certname")
in_query.add_query(extract_query)
log.error(in_query)
r = get_or_abort(
puppetdb.reports,
query=in_query,
order_by=order_args, …
=> Add subquery and in operators

setup.cfg
without this I get:
warning : [pytest] section in setup.cfg files is deprecated, use [tool:pytest] instead.
during: py.test --help
This PR fixes it. Tested on python 3.6
=> fix pytest section in setup.cfg

conftest.py, docs/quickstart.rst, pypuppetdb/__init__.py, pypuppetdb/api.py, tests/test_baseapi.py
This is a re-submission of https://github.com/voxpupuli/pypuppetdb/pull/102
```
docs/quickstart.rst - added documentation regarding RBAC token
authentication and how this is configured via connect()
pypuppetdb/init.py - added additional documentation for rbac token
authenticationa and defined token arg for passing to connect()
pypuppetdb/api.py - added support for RBAC token authentication and
ensured that session headers would contain the X-Authentication object
if a token is passed. Additionally, passing a token will force the
https protocol.
tests/test_baseapi.py - added tests for validating token argument
as well as session header tests and validation of protocols when
a token is passed
```
=> Added support for RBAC token authentication

pypuppetdb/api.py, tests/test_baseapi.py
* :bug: Fix a bug that prevented us from parsing results using dot-operator on the inventory endpoint
```
def inventory(self, **kwargs):
"""Get Node and Fact information with an alternative query syntax
for structured facts instead of using the facts, fact-contents and
factsets endpoints for many fact-related queries.
:param \*\*kwargs: The rest of the keyword arguments are passed
to the _query function.
:returns: A generator yielding Inventory
:rtype: :class:`pypuppetdb.types.Inventory`
"""
inventory = self._query('inventory', **kwargs)
for inv in inventory:
yield Inventory(
>               node=inv.certname,
time=inv.timestamp,
environment=inv.environment,
facts=inv.facts,
trusted=inv.trusted
)
E           AttributeError: 'dict' object has no attribute 'certname'
```
Also, these all use …
=> Fix bug with parsing results from inventory endpoint

pypuppetdb/api.py, tests/test_baseapi.py
The PuppetDB status endpoint returns a dictionary with status information
about the PuppetDB server.
https://puppet.com/docs/puppetdb/5.2/api/status/v1/status.html
=> Adding new endpoint: status

pypuppetdb/api.py, requirements.txt, tests/test_baseapi.py
PuppetDB will ignore query and filter specifications if the request is sent using POST and the query is sent in the querystring of the URI. Sending a POST request to PuppetDB with a query requires sending it in the body of the request.
This is not specifically documented that we have found, but is implied by the examples on the puppetdb documentation. It has been empirically tested, and our testing has shown this to be the case.
As an example, take a request to puppetdb for a specific node:
```
db.nodes(query='["=", "certname", "vm1.broker.dev"]')
```
If this request is sent as a POST, but not specifying that the query should be in the body, then the request will form encode the query in the URI, and PuppetDB will return the list of all nodes, rather than the specific node.
If this …
=> Send POST queries in body of request

pypuppetdb/api.py, tests/test_baseapi.py
This adds support for the cmd endpoint documented here:
https://puppet.com/docs/puppetdb/6.5/api/command/v1/commands.html
This satisfies part of https://github.com/voxpupuli/pypuppetdb/issues/135
I've added _cmd alongside _query to minimise changes to original code, as it would have required reworking _query quite a bit. 
This has been developed against the latest version of PuppetDB docs.
=> Add support for the Command API, /pdb/cmd/v1. 

pypuppetdb/QueryBuilder.py, tests/test_querybuilder.py
The [PuppetDB documentation][1] says that queries are JSON arrays, so
this commit updates all of the QueryBuilder classes to use lists/dicts
for the internal representation and defers the JSON serialization until
the `str()` call. This avoids having to manually quote things or do
string manipulation. `obj.json_data()` will return the native data
structure and `str(obj)` will return the serialized JSON.
Most of the changes to the tests are just fixing whitespace, but there
are a few places where duplicated quotes and backslash escaping were
fixed.
[1]: https://puppet.com/docs/puppetdb/5.1/api/query/v4/facts.html#url-parameters
Fixes: #140
Signed-off-by: Andrew Gunnerson <andrew.gunnerson@us.ibm.com>
=> QueryBuilder.py: Use native data structures for internal representation

pypuppetdb/api.py
As event-counts query may be very slow and has experimental
status it is beneficial for some users to get nodes without
exact number of changed resources in the last report
for compatibility and performance benefit.
=> Add option to get nodes without using event-counts

pytest.ini, requirements-test.txt, requirements.txt, setup.cfg
This resolves [Puppetboard issue 536](https://github.com/voxpupuli/puppetboard/issues/536)
In addition fixing coveralls, moving pytest configuration to single file and stopping pinning test packages.
=> Httpretty is not used outside tests and breaks install on newer python versions for some systems

pypuppetdb/api.py
to indicate verify_ssl can take a string. #143
=> BaseAPI ssl_verify: update the docstring

pypuppetdb/api.py, tests/test_baseapi.py
The v2 (Jolokia) metrics have been available for a while. They are in Puppet Server 5.3 and 6.9 so anything fairly recent is covered. The endpoint seems to be identical to v1 metrics, if you just strip away some additional information that gets returned.
This change is most important for Puppet Server 5.3.12 and 6.9.1 compatibility, released on 10 March 2020. Those releases fully disable the deprecated v1 metrics endpoints due to CVE-2020-7943.
Ref: #172.
=> Switch to Metrics API v2

CHANGELOG.rst, pypuppetdb/api.py, tests/test_baseapi.py
Several fixes / improvements here:
- With the new metrics v2 endpoint, special characters needed to be escaped out in order to properly pass them in the URL.
- Added a new `metrics()` function that returns a metrics list and fixed `metric()` when passed no parameters to return that list. In metrics v2 these the "list" and "read" are two different endpoints.
- Added all available metrics endpoints based on the Jolokia documentation: https://jolokia.org/reference/html/protocol.html
- Added a `payload` parameter to `_query()` so that people can pass arbitrary payloads during debugging (was helpful for me when figuring all of this stuff out with metrics escaping problems).
=> Metrics v2 fixes

requirements.txt
We do not need strictly pinned version of requests, the package works also with newer versions.
six is not used anywhere in the package.
=> Loosen requirements and drop six

docs/api.rst
Without a blank line like this, it just literally renders `.. autofunction:: connect`.
=> docs/api.rst: fix rendering of connect() docs

README.rst, docs/quickstart.rst, pypuppetdb/api.py, tests/test_connect.py
WIth this change it becomes possible to enclose puppetdb calls inside a "with" block so that all HTTP connections get explicitely closed when we're done.
I've had to explicitly close connections when working with paramiko for tunneling puppetdb requests through ssh.
=> Enable with statement

README.rst
Without cd, python complains can't open setup.py; if trying to run pypuppetdb/setup.py, it complains No such file or directory: 'README.rst'
=> setup.py requires presence of other files

docs/conf.py
as we (they?) are still using Python 2 there
=> Fix generating docs in readthedocs

.readthedocs.yaml, CONTRIBUTING.md, docs/requirements.txt, pypuppetdb/types.py
* We need to use Python 3 as we need to install pypuppetdb to get its code
parsed for autodoc
* Warnings in doc build mean that autodocs failed - this is critical,
as docs will be incomplete, so break such build
* Fix a warning from doc build
* Update info how to build the docs locally
=> Fix generating docs for Readthedocs

docs/developer.rst
in the developer docs.
Also add missing `Inventory` type to
the section about types.
=> Explain API and BaseAPI classes

docs/connecting.rst, pypuppetdb/types.py
in Sep 2020 (see
https://puppet.com/blog/removing-harmful-terminology-from-our-products/)
=> Rename components as Puppetlabs did it

.github/workflows/publish-to-pypi.yml, CONTRIBUTING.md, tbump.toml
thanks to a change in the release process:
use tags without the "v" prefix for releases.
To make it easier to remember document the
process and introduce a tool for it - tbump.
Note that we keep the "v" prefix in the
GitHub releases as there is no need
to change this.
=> Make rtd docs versioned

requirements-test.txt, tests/test_api_base_query.py, tests/test_connect.py
Utilize built-in unittest.mock instead of mock.
=> use unittest.mock instead of mock

MANIFEST.in
With PR #190 documentation files were renamed (`.rst` to `.md`).
=> Fix documentation files referenced in MANIFEST.in

.git-blame-ignore-revs, .github/workflows/linters.yml, .github/workflows/tests.yml, conftest.py, docs/conf.py, pypuppetdb/QueryBuilder.py, pypuppetdb/__init__.py, pypuppetdb/api/base.py, pypuppetdb/api/command.py, pypuppetdb/api/metadata.py, pypuppetdb/api/metrics.py, pypuppetdb/api/pql.py, pypuppetdb/api/query.py, pypuppetdb/api/status.py, pypuppetdb/errors.py, pypuppetdb/types.py, pypuppetdb/utils.py, setup.py, tests/test_api_base_init.py, tests/test_api_base_query.py, tests/test_api_base_url.py, tests/test_api_metrics.py, tests/test_api_other.py, tests/test_api_pql.py, tests/test_api_query.py, tests/test_connect.py, tests/test_querybuilder.py, tests/test_types.py, tests/test_utils.py
* Update syntax to Python 3.7+ with pyupgrade
* Format with black
=> Modernize the code
